# Generated by Django 4.0.2 on 2022-03-08 02:27

from django.db import migrations, models
import django.forms.widgets


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BmiUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('user_email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100, verbose_name=django.forms.widgets.PasswordInput)),
            ],
            options={
                'db_table': 'bmi_users',
            },
        ),
    ]
