# Generated by Django 4.0.2 on 2022-03-13 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appbmi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBmi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.CharField(max_length=20)),
                ('height', models.CharField(max_length=20)),
                ('bmi_unit', models.CharField(max_length=10)),
                ('bmi', models.CharField(max_length=20)),
                ('added_at', models.DateTimeField()),
                ('user_id', models.BigIntegerField()),
            ],
            options={
                'db_table': 'bmi_userbmi',
            },
        ),
        migrations.CreateModel(
            name='UserBmiLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bmi_id', models.BigIntegerField()),
                ('log_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'bmi_log',
            },
        ),
        migrations.CreateModel(
            name='UserDiet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bmi_index_range', models.CharField(max_length=10)),
                ('diet_description', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'bmi_diet',
            },
        ),
    ]
